Repository ALTERA-CAPSTON-41/backend, pull requests merged in 2022-07, with the labels that each got.

#54 feat: change to bearer auth
  libs/api-spec/api-spec.yml
  src/app/medical_record/handlers/handlers.go
  src/middlewares/authentication.go
  src/utils/jwt-auth.go
Labels: enhancement

#55 feat: add authentication restriction
  src/middlewares/authentication.go
  src/routes/route.go
Labels: enhancement

#57 docs: add query param for queue by polyclinic
  libs/api-spec/api-spec.yml
Labels: documentation

#59 fix(medical-record): can't show record by desired nik
  libs/api-spec/api-spec.yml
  src/app/medical_record/entity.go
  src/app/medical_record/handlers/handlers.go
  src/app/medical_record/mocks/Repositories.go
  src/app/medical_record/mocks/Services.go
  src/app/medical_record/repositories/mysql.go
  src/app/medical_record/services/usecases.go
  src/app/medical_record/services/usecases_test.go
  src/routes/route.go
Labels: bug, documentation, enhancement, refactor

#60 docs(api-spec): update medical record list by patient ID lookup
  libs/api-spec/api-spec.yml
Labels: documentation

#61 fix: allow CORS access
  src/routes/route.go
Labels: bug

#62 feat(prescription): add initial feature
  libs/api-spec/api-spec.yml
  main.go
  src/adapters/ca.go
  src/app/patient/handlers/handlers.go
  src/app/prescription/entity.go
  src/app/prescription/factories/factory.go
  src/app/prescription/handlers/handlers.go
  src/app/prescription/handlers/request/dto.go
  src/app/prescription/handlers/response/dto.go
  src/app/prescription/mocks/Repositories.go
  src/app/prescription/mocks/Services.go
  src/app/prescription/repositories/mysql.go
  src/app/prescription/repositories/record.go
  src/app/prescription/services/usecases.go
  src/app/prescription/services/usecases_test.go
  src/routes/route.go
Labels: documentation, enhancement

#63 feat(polyclinic): add get all with stats
  src/app/polyclinic/entity.go
  src/app/polyclinic/handlers/handlers.go
  src/app/polyclinic/handlers/response/dto.go
  src/app/polyclinic/mocks/Repositories.go
  src/app/polyclinic/mocks/Services.go
  src/app/polyclinic/repositories/mysql.go
  src/app/polyclinic/services/usecases.go
  src/app/polyclinic/services/usecases_test.go
  src/routes/route.go
Labels: documentation, enhancement

#66 feat(medical-record): add patient status
  libs/api-spec/api-spec.yml
  src/app/medical_record/entity.go
  src/app/medical_record/handlers/request/dto.go
  src/app/medical_record/handlers/response/dto.go
  src/app/medical_record/repositories/mysql.go
  src/app/medical_record/repositories/record.go
  src/app/medical_record/services/usecases_test.go
Labels: enhancement

#65 feat(admin, doctor, nurse, patient): add input validation
  go.mod
  go.sum
  src/app/admin/handlers/handlers.go
  src/app/admin/handlers/request/dto.go
  src/app/doctor/handlers/handlers.go
  src/app/doctor/handlers/request/dto.go
  src/app/doctor/handlers/response/dto.go
  src/app/nurse/handlers/handlers.go
  src/app/nurse/handlers/request/dto.go
  src/app/nurse/handlers/response/dto.go
  src/app/patient/handlers/handlers.go
  src/app/patient/handlers/request/dto.go
  src/app/patient/handlers/response/dto.go
Labels: enhancement

#67 feat(doctor, nurse): lookup by polyclinic
  libs/api-spec/api-spec.yml
  src/app/doctor/entity.go
  src/app/doctor/handlers/handlers.go
  src/app/doctor/mocks/Repositories.go
  src/app/doctor/mocks/Services.go
  src/app/doctor/repositories/mysql.go
  src/app/doctor/services/usecases.go
  src/app/doctor/services/usecases_test.go
  src/app/nurse/entity.go
  src/app/nurse/handlers/handlers.go
  src/app/nurse/mocks/Repositories.go
  src/app/nurse/mocks/Services.go
  src/app/nurse/repositories/mysql.go
  src/app/nurse/services/usecases.go
  src/app/nurse/services/usecases_test.go
  src/app/patient/handlers/handlers.go
  src/app/patient/handlers/response/dto.go
Labels: documentation, enhancement, refactor

#70 ci: separate PR and push workflow and add `codecov`
  .github/workflows/on_pr_master.yml
  .github/workflows/on_push_master.yml
  codecov.yml
Labels: automation

#68 feat(medical-record): add update and remove feature
  libs/api-spec/api-spec.yml
  src/app/medical_record/entity.go
  src/app/medical_record/handlers/handlers.go
  src/app/medical_record/handlers/request/dto.go
  src/app/medical_record/mocks/Repositories.go
  src/app/medical_record/mocks/Services.go
  src/app/medical_record/repositories/mysql.go
  src/app/medical_record/repositories/record.go
  src/app/medical_record/services/usecases.go
  src/app/medical_record/services/usecases_test.go
  src/routes/route.go
Labels: enhancement

#69 feat(queue): frontend should not to add time manually
  libs/api-spec/api-spec.yml
  src/app/queue/handlers/request/dto.go
  src/app/queue/repositories/mysql.go
Labels: enhancement

#71 feat(admin, doctor, nurse, patient): add name validation
  src/app/admin/handlers/handlers.go
  src/app/admin/handlers/response/dto.go
  src/app/doctor/handlers/handlers.go
  src/app/nurse/handlers/handlers.go
  src/app/patient/handlers/handlers.go
  src/utils/validate-name.go
Labels: enhancement

#72 refactor(patient): make NIK to be unique
  src/app/patient/handlers/handlers.go
  src/app/patient/repositories/record.go
Labels: refactor

#73 fix(admin, patient): update & deletion always return not found
  src/app/admin/repositories/mysql.go
  src/app/patient/repositories/mysql.go
Labels: bug

#74 docs: complete readme and guides
  CONTRIBUTING.md
  README.md
  libs/api-spec/api-spec.yml
  libs/dbml/clinic.dbml
  public/html/api-spec.html
Labels: documentation

#75 fix(admin): avoid self delete on admin role
  src/app/admin/handlers/handlers.go
Labels: bug
