Repository ALTERA-CAPSTON-41/backend, pull requests merged in 2022-06, with the labels that each got.

#21 build(docker): add `.env` to build phase
  .github/workflows/on_push_pr.yml
  Dockerfile
Labels: automation

#23 feat(admin): add feature as initial
  go.mod
  go.sum
  main.go
  src/adapters/ca.go
  src/app/admin/entity.go
  src/app/admin/factories/factory.go
  src/app/admin/handlers/handlers.go
  src/app/admin/handlers/request/dto.go
  src/app/admin/handlers/response/dto.go
  src/app/admin/mocks/Repositories.go
  src/app/admin/mocks/Services.go
  src/app/admin/repositories/mysql.go
  src/app/admin/repositories/record.go
  src/app/admin/services/usecases.go
  src/app/admin/services/usecases_test.go
  src/routes/route.go
Labels: enhancement

#26 refactor(polyclinic): migrate to clean architecture
  main.go
  src/adapters/ca.go
  src/app/polyclinic/entity.go
  src/app/polyclinic/factories/factory.go
  src/app/polyclinic/handlers/handlers.go
  src/app/polyclinic/handlers/request/dto.go
  src/app/polyclinic/handlers/response/dto.go
  src/app/polyclinic/mocks/Repositories.go
  src/app/polyclinic/mocks/Services.go
  src/app/polyclinic/repositories/mysql.go
  src/app/polyclinic/repositories/record.go
  src/app/polyclinic/services/usecases.go
  src/app/polyclinic/services/usecases_test.go
  src/handlers/polyclinic_handler.go
  src/models/init.go
  src/models/polyclinic.go
  src/routes/route.go
Labels: refactor

#27 refactor(queue): migrate to clean architecture
  main.go
  src/adapters/ca.go
  src/app/polyclinic/repositories/mysql.go
  src/app/queue/entity.go
  src/app/queue/factories/factory.go
  src/app/queue/handlers/handlers.go
  src/app/queue/handlers/request/dto.go
  src/app/queue/handlers/response/dto.go
  src/app/queue/mocks/Repositories.go
  src/app/queue/mocks/Services.go
  src/app/queue/repositories/mysql.go
  src/app/queue/repositories/record.go
  src/app/queue/services/usecases.go
  src/app/queue/services/usecases_test.go
  src/handlers/queue_handler.go
  src/models/queue.go
  src/models/type.go
  src/routes/route.go
  src/types/enums.go
Labels: refactor

#28 refactor(doctor): migrate to CA basecode
  main.go
  src/adapters/ca.go
  src/app/admin/repositories/record.go
  src/app/doctor/entity.go
  src/app/doctor/factories/factory.go
  src/app/doctor/handlers/handlers.go
  src/app/doctor/handlers/request/dto.go
  src/app/doctor/handlers/response/dto.go
  src/app/doctor/mocks/Repositories.go
  src/app/doctor/mocks/Services.go
  src/app/doctor/repositories/mysql.go
  src/app/doctor/repositories/record.go
  src/app/doctor/services/usecases.go
  src/app/doctor/services/usecases_test.go
  src/app/queue/entity.go
  src/app/queue/repositories/record.go
  src/handlers/doctor_handler.go
  src/handlers/user_handler.go
  src/models/doctor.go
  src/models/user.go
  src/routes/route.go
  src/types/enums.go
Labels: refactor

#30 docs(api-spec): revise api-spec into a proper response and request
  libs/api-spec/api-spec.yml
Labels: documentation

#32 docs(api-spec): revise example responses
  libs/api-spec/api-spec.yml
  public/html/api-spec.html
Labels: documentation

#33 ci: add image push to `ghcr.io` and change deployment workflow
  .github/workflows/on_push_pr.yml
  Dockerfile
Labels: automation

#35 refactor(account): migrate to CA
  main.go
  src/adapters/ca.go
  src/app/account/entity.go
  src/app/account/factories/factory.go
  src/app/account/handlers/handlers.go
  src/app/account/handlers/request/dto.go
  src/app/account/handlers/response/dto.go
  src/app/account/mocks/Repositories.go
  src/app/account/mocks/Services.go
  src/app/account/repositories/mysql.go
  src/app/account/repositories/record.go
  src/app/account/services/usecases.go
  src/app/account/services/usecases_test.go
  src/handlers/user_handler.go
  src/models/user.go
  src/routes/route.go
  src/utils/jwt-auth.go
Labels: refactor

#37 feat(nurse): add initial feature
  libs/api-spec/api-spec.yml
  main.go
  public/html/api-spec.html
  src/adapters/ca.go
  src/app/nurse/entity.go
  src/app/nurse/factories/factory.go
  src/app/nurse/handlers/handlers.go
  src/app/nurse/handlers/request/dto.go
  src/app/nurse/handlers/response/dto.go
  src/app/nurse/mocks/Repositories.go
  src/app/nurse/mocks/Services.go
  src/app/nurse/repositories/mysql.go
  src/app/nurse/repositories/record.go
  src/app/nurse/services/usecases.go
  src/app/nurse/services/usecases_test.go
  src/routes/route.go
Labels: enhancement

#39 fix(api-spec): elements docs need pre-hosted `api-spec.yml`
  Dockerfile
  public/html/api-spec.html
  src/app/apispec/handlers/handlers.go
  src/routes/route.go
Labels: bug

#41 feat(user): add delete user
  src/app/admin/entity.go
  src/app/admin/mocks/Repositories.go
  src/app/admin/repositories/mysql.go
  src/app/admin/services/usecases.go
  src/app/admin/services/usecases_test.go
  src/app/doctor/entity.go
  src/app/doctor/mocks/Repositories.go
  src/app/doctor/repositories/mysql.go
  src/app/doctor/services/usecases.go
  src/app/doctor/services/usecases_test.go
  src/app/nurse/entity.go
  src/app/nurse/mocks/Repositories.go
  src/app/nurse/repositories/mysql.go
  src/app/nurse/services/usecases.go
  src/app/nurse/services/usecases_test.go
Labels: enhancement

#42 feat(doctor, nurse, patient, queue): implement pagination
  src/app/doctor/entity.go
  src/app/doctor/handlers/handlers.go
  src/app/doctor/mocks/Repositories.go
  src/app/doctor/repositories/mysql.go
  src/app/doctor/services/usecases.go
  src/app/doctor/services/usecases_test.go
  src/app/nurse/entity.go
  src/app/nurse/handlers/handlers.go
  src/app/nurse/mocks/Repositories.go
  src/app/nurse/repositories/mysql.go
  src/app/nurse/services/usecases.go
  src/app/nurse/services/usecases_test.go
  src/app/patient/entity.go
  src/app/patient/handlers/handlers.go
  src/app/patient/mocks/Repositories.go
  src/app/patient/repositories/mysql.go
  src/app/patient/services/usecases.go
  src/app/patient/services/usecases_test.go
  src/app/queue/entity.go
  src/app/queue/handlers/handlers.go
  src/app/queue/mocks/Repositories.go
  src/app/queue/repositories/mysql.go
  src/app/queue/services/usecases.go
  src/app/queue/services/usecases_test.go
Labels: enhancement

#43 chore: add error logging
  .github/workflows/on_push_pr.yml
  Dockerfile
  README.md
  example.env
  go.mod
  go.sum
  main.go
  src/app/account/handlers/handlers.go
  src/app/admin/handlers/handlers.go
  src/app/doctor/handlers/handlers.go
  src/app/nurse/handlers/handlers.go
  src/app/patient/handlers/handlers.go
  src/app/polyclinic/handlers/handlers.go
  src/app/queue/handlers/handlers.go
  src/configs/environment.go
  src/database/mongodb.go
  src/database/mysql.go
  src/utils/logrus-logging.go
Labels: enhancement

#45 feat(dashboard): add initial feature
  libs/api-spec/api-spec.yml
  src/adapters/ca.go
  src/app/dashboard/entity.go
  src/app/dashboard/factories/factory.go
  src/app/dashboard/handlers/handlers.go
  src/app/dashboard/handlers/response/dto.go
  src/app/dashboard/mocks/Repositories.go
  src/app/dashboard/mocks/Services.go
  src/app/dashboard/repositories/mysql.go
  src/app/dashboard/services/usecases.go
  src/app/dashboard/services/usecases_test.go
  src/routes/route.go
Labels: documentation, enhancement

#46 feat(medical_record): add initial feature
  go.mod
  go.sum
  libs/api-spec/api-spec.yml
  main.go
  src/adapters/ca.go
  src/app/medical_record/entity.go
  src/app/medical_record/factories/factory.go
  src/app/medical_record/handlers/handlers.go
  src/app/medical_record/handlers/request/dto.go
  src/app/medical_record/handlers/response/dto.go
  src/app/medical_record/mocks/Repositories.go
  src/app/medical_record/mocks/Services.go
  src/app/medical_record/repositories/mysql.go
  src/app/medical_record/repositories/record.go
  src/app/medical_record/services/usecases.go
  src/app/medical_record/services/usecases_test.go
  src/middlewares/authentication.go
  src/routes/route.go
  src/utils/interval-calculation.go
  src/utils/jwt-auth.go
Labels: enhancement

#48 feat(icd10): add initial feature
  libs/api-spec/api-spec.yml
  src/adapters/ca.go
  src/app/icd10/entity.go
  src/app/icd10/factories/factory.go
  src/app/icd10/handlers/handlers.go
  src/app/icd10/handlers/response/dto.go
  src/app/icd10/mocks/Repositories.go
  src/app/icd10/mocks/Services.go
  src/app/icd10/repositories/mysql.go
  src/app/icd10/repositories/record.go
  src/app/icd10/services/usecase.go
  src/app/icd10/services/usecase_test.go
  src/routes/route.go
Labels: enhancement

#47 fix: can't verify authentication
  src/middlewares/authentication.go
  src/routes/route.go
Labels: bug

#49 fix: can't determine the email is already used
  README.md
  src/app/admin/entity.go
  src/app/admin/handlers/handlers.go
  src/app/admin/handlers/response/dto.go
  src/app/admin/mocks/Repositories.go
  src/app/admin/mocks/Services.go
  src/app/admin/repositories/mysql.go
  src/app/admin/services/usecases.go
  src/app/admin/services/usecases_test.go
  src/app/doctor/entity.go
  src/app/doctor/handlers/handlers.go
  src/app/doctor/handlers/response/dto.go
  src/app/doctor/mocks/Repositories.go
  src/app/doctor/mocks/Services.go
  src/app/doctor/repositories/mysql.go
  src/app/doctor/services/usecases.go
  src/app/doctor/services/usecases_test.go
  src/app/nurse/entity.go
  src/app/nurse/handlers/handlers.go
  src/app/nurse/handlers/response/dto.go
  src/app/nurse/mocks/Repositories.go
  src/app/nurse/mocks/Services.go
  src/app/nurse/repositories/mysql.go
  src/app/nurse/services/usecases.go
  src/app/nurse/services/usecases_test.go
  src/middlewares/authentication.go
Labels: enhancement
